---
# tasks file for kubernetes-setup
#
#
- name: Bring private ip of remote master server
  set_fact:
    mprivateip: "{{ ansible_eth0.ipv4.address }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['master'] }}"


- debug: 
    msg: "This is a private IP address of master :{{ mprivateip }}"
  register: picip


- include_tasks: kube-packges.yml

- include_tasks: kube-init.yml
   
- include_tasks: create-dir.yml

- include_tasks: pod-nw.yml

- include_tasks: create-token.yml

- include_tasks: join.yml

 
