---
- hosts: master
  become: true
  pre_tasks: 
    - name: Bring private ip of remote server
      set_fact:
        mprivateip: "{{ ansible_eth0.ipv4.address }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['master'] }}"
      

  roles: 
    - kubernetes-setup

